# Generated by Django 2.1 on 2018-08-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='상품명')),
                ('product_price', models.CharField(max_length=100, verbose_name='가격')),
                ('product_register', models.DateTimeField(auto_now_add=True, verbose_name='상품 등록일')),
                ('product_detail', models.TextField(verbose_name='상품 설명')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('star', models.CharField(blank=True, choices=[('1', '1점'), ('2', '2점'), ('3', '3점'), ('4', '4점'), ('5', '5점')], max_length=1, verbose_name='평점')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
