# Generated by Django 2.1 on 2018-08-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='spend',
        ),
    ]
