# Generated by Django 2.1 on 2018-08-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180811_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_before',
            field=models.CharField(default=1, max_length=100, verbose_name='정가'),
            preserve_default=False,
        ),
    ]
