# Generated by Django 2.1 on 2018-08-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_product_product_price_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='평점'),
        ),
    ]
