# Generated by Django 2.1 on 2018-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180814_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='', verbose_name='상품 사진'),
        ),
    ]
