# Generated by Django 2.1 on 2018-08-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20180814_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=1, verbose_name='평점'),
        ),
    ]
