# Generated by Django 2.1 on 2018-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20180818_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.IntegerField(choices=[(1, '밀스 라이트'), (2, '피로그래밍')], default=1, max_length=1, verbose_name='카테고리'),
            preserve_default=False,
        ),
    ]
