# Generated by Django 2.1 on 2018-08-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category2',
            new_name='category',
        ),
    ]
